use cdde_core::Result;
use cdde_proto::{ActionType, DiameterPacketAction, DiameterPacketRequest};

// Import generated proto types
// Note: In a real implementation, we would import the client generated by tonic-build
// For now, we'll define a wrapper that simulates the client interaction or uses the proto definitions directly

/// DCR Client wrapper
#[derive(Clone)]
pub struct DcrClient {
    // In a real app: client: CoreRouterServiceClient<Channel>
    // For now we store the channel endpoint
    pub endpoint: String,
}

impl DcrClient {
    /// Create new DCR client
    pub fn new(endpoint: String) -> Self {
        Self { endpoint }
    }

    /// Connect to DCR (placeholder)
    pub async fn connect(&self) -> Result<()> {
        // In real implementation: Channel::from_shared(endpoint)?.connect().await?;
        Ok(())
    }

    /// Send packet to DCR
    pub async fn send_packet(
        &self,
        request: DiameterPacketRequest,
    ) -> Result<DiameterPacketAction> {
        // Placeholder for actual gRPC call
        // let response = self.client.process_packet(Request::new(request)).await?;
        // Ok(response.into_inner())

        // For testing/mocking purposes without a running server:
        Ok(DiameterPacketAction {
            action_type: ActionType::Forward as i32,
            target_host_name: "mock-target".to_string(),
            response_payload: request.raw_payload, // Echo back
            original_connection_id: request.connection_id,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_client_creation() {
        let client = DcrClient::new("http://[::1]:50051".to_string());
        assert_eq!(client.endpoint, "http://[::1]:50051");
    }

    #[tokio::test]
    async fn test_send_packet_mock() {
        let client = DcrClient::new("http://mock".to_string());

        let request = DiameterPacketRequest {
            connection_id: 123,
            vr_id: "vr1".to_string(),
            reception_timestamp: 1000,
            raw_payload: vec![1, 2, 3],
            session_tx_id: 456,
        };

        let response = client.send_packet(request).await.unwrap();
        assert_eq!(response.original_connection_id, 123);
        assert_eq!(response.response_payload, vec![1, 2, 3]);
    }
}
